### ISSUE TITLE
helper#extract_image() does not match images with query string in the URL

### ISSUE THREAD

**Issue by mentos** [AlfredoRamos/phpbb-ext-seo-metadata#81]
[`helper#extract_image()`](https://github.com/AlfredoRamos/phpbb-ext-seo-metadata/blob/master/includes/helper.php#L795) does not match images containing a query string in their URL. For example the following image will be ignore due to `\.(?:jpe?g|png|gif)$` looking for the file extension to be the last thing in the URL: `<img src="www.example.com/my-image.jpg?h=400&w=500" alt="" />`. 

Query strings in images src is useful when dealing with dynamically sized images and/or caching mechanisms that rely on URL params for cache expiration, so this might be something you want to consider for this extension.

**Comment by AlfredoRamos** [comment]
Hi :wave: 

Thanks for the report, it should be fixed once #82 is merged.
