### ISSUE TITLE
Does upgrade require complete uninstall? (bug or feat. request)

### ISSUE THREAD

**Issue by pms967** [AlfredoRamos/phpbb-ext-seo-metadata#83]
Hi,

does upgrading from a previous version requires:

1) a complete **uninstall** (including deleting its data, that is the configuration) or 

2) is it enough to **disable** the extension, delete the files under /forum/ext/ , replace them with the new version and then enable the extension again, without the need to delete data and thus re-enter the config from scratch?

If it's true the former (1), take this as a feature request: if possible, please avoid that need, as having to re-enter the config at every update is quite inconvenient. 

OTOH, if it's true the latter (2) then there's a bug in the README.md file, as in the upgrade instructions it states "Uninstall the extension" rather then "Disable the extension".

Thanks.  :-)

**Comment by AlfredoRamos** [comment]
Hi :wave:

Yes, it's enough if you only disable the extension before deleting the old files, uploading the new version and enabling the extension again.

I'll fix the instructions ;)
