### ISSUE TITLE
Og:image doesn't have a default

### ISSUE THREAD

**Issue by Stinggy** [AlfredoRamos/phpbb-ext-seo-metadata#95]
Is there a way to set a default og:image like a logo if it cannot find a image in a post for Facebook.

Thanks

**Comment by AlfredoRamos** [comment]
> Og:image doesn't have a default

That's not true.

It already generates a default image for both Open Graph and Twitter Cards when you set the default image in the extension settings page in the ACP.

If you don't see the change in some social networks it means that that post/topic was shared or fetched before and the previous cached data is being used. That's managed by said social network.

For Facebook specifically, you can use the [Open Graph Object Debugger](https://developers.facebook.com/tools/debug/og/object/) to force clean the cache.
